// Package core contains the pure domain models and business rules for Memorit.
//
// This package has zero dependencies on external infrastructure or frameworks
// (except standard library and minimal cryptographic dependencies for ID generation).
// All other layers of the application depend on types defined here.
//
// The core domain includes:
//   - Domain models (ChatRecord, Concept, ConceptRef)
//   - Value objects (ID, SpeakerType)
//   - Domain validation rules
//   - Domain-specific errors
//
// Domain validation rules apply to the core business invariants only.
// Validation does NOT include:
//   - Vector embeddings (generated by processors)
//   - Concept references (populated by processors)
//   - Non-zero IDs (0 is valid from database sequences)
//
// This follows the principles of Clean Architecture and Hexagonal Architecture,
// keeping the domain isolated from infrastructure concerns.
package core
