// Copyright 2025 Poiesic Systems
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


// Package core contains the pure domain models and business rules for Memorit.
//
// This package has zero dependencies on external infrastructure or frameworks
// (except standard library and minimal cryptographic dependencies for ID generation).
// All other layers of the application depend on types defined here.
//
// The core domain includes:
//   - Domain models (ChatRecord, Concept, ConceptRef)
//   - Value objects (ID, SpeakerType)
//   - Domain validation rules
//   - Domain-specific errors
//
// Domain validation rules apply to the core business invariants only.
// Validation does NOT include:
//   - Vector embeddings (generated by processors)
//   - Concept references (populated by processors)
//   - Non-zero IDs (0 is valid from database sequences)
//
// This follows the principles of Clean Architecture and Hexagonal Architecture,
// keeping the domain isolated from infrastructure concerns.
package core
